"""rebuild relationships

Revision ID: d8b654680c0a
Revises: a2c9a02bbf9f
Create Date: 2025-09-05 17:01:48.948620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b654680c0a'
down_revision: Union[str, Sequence[str], None] = 'a2c9a02bbf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('drink_adds_drink_id_fkey'), 'drink_adds', type_='foreignkey')
    op.drop_constraint(op.f('drink_adds_add_id_fkey'), 'drink_adds', type_='foreignkey')
    op.create_foreign_key(None, 'drink_adds', 'adds', ['add_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'drink_adds', 'drinks', ['drink_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('drink_sizes_size_id_fkey'), 'drink_sizes', type_='foreignkey')
    op.drop_constraint(op.f('drink_sizes_drink_id_fkey'), 'drink_sizes', type_='foreignkey')
    op.create_foreign_key(None, 'drink_sizes', 'drinks', ['drink_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'drink_sizes', 'sizes', ['size_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('drinks_created_by_fkey'), 'drinks', type_='foreignkey')
    op.drop_constraint(op.f('drinks_type_id_fkey'), 'drinks', type_='foreignkey')
    op.create_foreign_key(None, 'drinks', 'drink_types', ['type_id'], ['id'], source_schema='public', referent_schema='public', ondelete='RESTRICT')
    op.create_foreign_key(None, 'drinks', 'users', ['created_by'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('images_drink_id_fkey'), 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'drinks', ['drink_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('order_adds_order_id_fkey'), 'order_adds', type_='foreignkey')
    op.drop_constraint(op.f('order_adds_add_id_fkey'), 'order_adds', type_='foreignkey')
    op.create_foreign_key(None, 'order_adds', 'orders', ['order_id'], ['id'], source_schema='public', referent_schema='public', ondelete='RESTRICT')
    op.create_foreign_key(None, 'order_adds', 'adds', ['add_id'], ['id'], source_schema='public', referent_schema='public', ondelete='RESTRICT')
    op.drop_constraint(op.f('orders_drink_size_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_tg_user_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_status_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['tg_user_id'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'drink_sizes', ['drink_size_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'order_statuses', ['status_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('sessions_tg_user_id_fkey'), 'sessions', type_='foreignkey')
    op.drop_constraint(op.f('sessions_role_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public', ondelete='SET DEFAULT')
    op.create_foreign_key(None, 'sessions', 'users', ['tg_user_id'], ['tg_user_id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_role_id_fkey'), 'sessions', 'roles', ['role_id'], ['id'], ondelete='SET DEFAULT')
    op.create_foreign_key(op.f('sessions_tg_user_id_fkey'), 'sessions', 'users', ['tg_user_id'], ['tg_user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'orders', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('orders_status_id_fkey'), 'orders', 'order_statuses', ['status_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_tg_user_id_fkey'), 'orders', 'users', ['tg_user_id'], ['tg_user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_drink_size_id_fkey'), 'orders', 'drink_sizes', ['drink_size_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'order_adds', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'order_adds', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('order_adds_add_id_fkey'), 'order_adds', 'adds', ['add_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('order_adds_order_id_fkey'), 'order_adds', 'orders', ['order_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'images', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('images_drink_id_fkey'), 'images', 'drinks', ['drink_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'drinks', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'drinks', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('drinks_type_id_fkey'), 'drinks', 'drink_types', ['type_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('drinks_created_by_fkey'), 'drinks', 'users', ['created_by'], ['tg_user_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'drink_sizes', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'drink_sizes', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('drink_sizes_drink_id_fkey'), 'drink_sizes', 'drinks', ['drink_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('drink_sizes_size_id_fkey'), 'drink_sizes', 'sizes', ['size_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'drink_adds', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'drink_adds', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('drink_adds_add_id_fkey'), 'drink_adds', 'adds', ['add_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('drink_adds_drink_id_fkey'), 'drink_adds', 'drinks', ['drink_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
